//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ABCD : DbContext
    {
        public ABCD()
            : base("name=ABCD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<student> students { get; set; }
    
        public virtual int Sp_DeleteStudent(Nullable<int> rollnumber)
        {
            var rollnumberParameter = rollnumber.HasValue ?
                new ObjectParameter("Rollnumber", rollnumber) :
                new ObjectParameter("Rollnumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_DeleteStudent", rollnumberParameter);
        }
    
        public virtual int Sp_INsertData(string name, Nullable<int> age, string email)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_INsertData", nameParameter, ageParameter, emailParameter);
        }
    
        public virtual int sp_UpdateStudent(Nullable<int> rollnumber, string name, Nullable<int> age, string email)
        {
            var rollnumberParameter = rollnumber.HasValue ?
                new ObjectParameter("Rollnumber", rollnumber) :
                new ObjectParameter("Rollnumber", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateStudent", rollnumberParameter, nameParameter, ageParameter, emailParameter);
        }
    }
}
